### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Ehesp** [wwebdev/separator-generator#3]
Great tool! Stuff like this comes in handy. I can see a couple of minor things which I picked up on, via the website generator:

1) "Bite Marks" with large size and position shows a border:

![image](https://user-images.githubusercontent.com/842078/80275978-254e3c00-86dd-11ea-8a7b-56511fd35661.png)

2) The curve starts to show a notch when being set on a higher curve rate:

![image](https://user-images.githubusercontent.com/842078/80275997-4151dd80-86dd-11ea-91ad-3a569f94fa55.png)

**Comment by tomByrer** [comment]
Yes, I've noticed the same in Chromium browsers on Win10.

As a side note, I tried to switch the HTML from `<div>` to `<br>`, but looks like they render differently.
wave: https://codepen.io/tomByrer/pen/dyYvadx
sawtooth: https://codepen.io/tomByrer/pen/xxwqMpm
skewed: (Still is off in Firefox with div) https://codepen.io/tomByrer/pen/PoPpVdG

**Comment by Vincenius** [comment]
Thanks for the feedback - I'll look into that during this week

**Comment by Vincenius** [comment]
The issue with the "Bite Marks" should be resolved now.

**Comment by Vincenius** [comment]
After fiddling with the wave variables for quite a while I could reduce the notch - still isn't perfect but I think it's good enough 😅
